// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Outer struct {
	OuterValue           *Inner   `protobuf:"bytes,1,opt,name=outer_value,json=outerValue,proto3" json:"outer_value,omitempty"`
	OuterNum             int64    `protobuf:"varint,2,opt,name=outer_num,json=outerNum,proto3" json:"outer_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outer) Reset()         { *m = Outer{} }
func (m *Outer) String() string { return proto.CompactTextString(m) }
func (*Outer) ProtoMessage()    {}
func (*Outer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Outer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outer.Unmarshal(m, b)
}
func (m *Outer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outer.Marshal(b, m, deterministic)
}
func (m *Outer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outer.Merge(m, src)
}
func (m *Outer) XXX_Size() int {
	return xxx_messageInfo_Outer.Size(m)
}
func (m *Outer) XXX_DiscardUnknown() {
	xxx_messageInfo_Outer.DiscardUnknown(m)
}

var xxx_messageInfo_Outer proto.InternalMessageInfo

func (m *Outer) GetOuterValue() *Inner {
	if m != nil {
		return m.OuterValue
	}
	return nil
}

func (m *Outer) GetOuterNum() int64 {
	if m != nil {
		return m.OuterNum
	}
	return 0
}

type Inner struct {
	InnerValue           string   `protobuf:"bytes,3,opt,name=inner_value,json=innerValue,proto3" json:"inner_value,omitempty"`
	InnerNum             int64    `protobuf:"varint,4,opt,name=inner_num,json=innerNum,proto3" json:"inner_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inner) Reset()         { *m = Inner{} }
func (m *Inner) String() string { return proto.CompactTextString(m) }
func (*Inner) ProtoMessage()    {}
func (*Inner) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *Inner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inner.Unmarshal(m, b)
}
func (m *Inner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inner.Marshal(b, m, deterministic)
}
func (m *Inner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inner.Merge(m, src)
}
func (m *Inner) XXX_Size() int {
	return xxx_messageInfo_Inner.Size(m)
}
func (m *Inner) XXX_DiscardUnknown() {
	xxx_messageInfo_Inner.DiscardUnknown(m)
}

var xxx_messageInfo_Inner proto.InternalMessageInfo

func (m *Inner) GetInnerValue() string {
	if m != nil {
		return m.InnerValue
	}
	return ""
}

func (m *Inner) GetInnerNum() int64 {
	if m != nil {
		return m.InnerNum
	}
	return 0
}

type OuterWithExtra struct {
	OuterValue           *Inner   `protobuf:"bytes,1,opt,name=outer_value,json=outerValue,proto3" json:"outer_value,omitempty"`
	OuterNum             int64    `protobuf:"varint,2,opt,name=outer_num,json=outerNum,proto3" json:"outer_num,omitempty"`
	ExtraField           string   `protobuf:"bytes,3,opt,name=extra_field,json=extraField,proto3" json:"extra_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OuterWithExtra) Reset()         { *m = OuterWithExtra{} }
func (m *OuterWithExtra) String() string { return proto.CompactTextString(m) }
func (*OuterWithExtra) ProtoMessage()    {}
func (*OuterWithExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *OuterWithExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OuterWithExtra.Unmarshal(m, b)
}
func (m *OuterWithExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OuterWithExtra.Marshal(b, m, deterministic)
}
func (m *OuterWithExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OuterWithExtra.Merge(m, src)
}
func (m *OuterWithExtra) XXX_Size() int {
	return xxx_messageInfo_OuterWithExtra.Size(m)
}
func (m *OuterWithExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_OuterWithExtra.DiscardUnknown(m)
}

var xxx_messageInfo_OuterWithExtra proto.InternalMessageInfo

func (m *OuterWithExtra) GetOuterValue() *Inner {
	if m != nil {
		return m.OuterValue
	}
	return nil
}

func (m *OuterWithExtra) GetOuterNum() int64 {
	if m != nil {
		return m.OuterNum
	}
	return 0
}

func (m *OuterWithExtra) GetExtraField() string {
	if m != nil {
		return m.ExtraField
	}
	return ""
}

func init() {
	proto.RegisterType((*Outer)(nil), "bradleyjkemp.github.io.Outer")
	proto.RegisterType((*Inner)(nil), "bradleyjkemp.github.io.Inner")
	proto.RegisterType((*OuterWithExtra)(nil), "bradleyjkemp.github.io.OuterWithExtra")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x31, 0xa5, 0x88, 0x5e, 0x24, 0x06, 0x0f, 0x55, 0x05, 0x42, 0x44, 0x99, 0x32, 0x79,
	0x28, 0x3b, 0x0b, 0x2a, 0x12, 0x0b, 0x48, 0xe1, 0x73, 0xab, 0x12, 0x72, 0xb4, 0x86, 0xc4, 0x2e,
	0xce, 0xb9, 0xa2, 0x7f, 0x82, 0xdf, 0x8c, 0xee, 0x02, 0x4c, 0xc0, 0xc6, 0x76, 0x79, 0xe3, 0xe7,
	0xbd, 0xc7, 0x32, 0x00, 0x61, 0x47, 0x66, 0x15, 0x3c, 0x79, 0x3d, 0xae, 0x42, 0x59, 0x37, 0xb8,
	0x79, 0x7e, 0xc1, 0x76, 0x65, 0x16, 0x96, 0x96, 0xb1, 0x32, 0xd6, 0x67, 0x35, 0x0c, 0xaf, 0x22,
	0x61, 0xd0, 0xa7, 0x90, 0x78, 0x1e, 0xe6, 0xeb, 0xb2, 0x89, 0x38, 0x51, 0xa9, 0xca, 0x93, 0xe9,
	0x91, 0xf9, 0x19, 0x33, 0x17, 0xce, 0x61, 0x28, 0x40, 0x88, 0x3b, 0x06, 0xf4, 0x21, 0x8c, 0x7a,
	0xde, 0xc5, 0x76, 0xb2, 0x9d, 0xaa, 0x7c, 0x50, 0xec, 0x49, 0x70, 0x19, 0xdb, 0x6c, 0x06, 0x43,
	0x21, 0xf4, 0x31, 0x24, 0x96, 0x87, 0xcf, 0x2d, 0x83, 0x54, 0xe5, 0xa3, 0x02, 0x24, 0xfa, 0xae,
	0xe9, 0x0f, 0x70, 0xcd, 0x4e, 0x5f, 0x23, 0x01, 0xd7, 0xbc, 0x2b, 0xd8, 0x17, 0xdb, 0x7b, 0x4b,
	0xcb, 0xd9, 0x1b, 0x85, 0xf2, 0x5f, 0xb5, 0xd9, 0x16, 0x79, 0xcb, 0xfc, 0xc9, 0x62, 0x53, 0x7f,
	0xd9, 0x4a, 0x74, 0xce, 0xc9, 0x74, 0x01, 0xc9, 0x0d, 0x76, 0x74, 0x8d, 0x61, 0x6d, 0x1f, 0x51,
	0x3f, 0xc0, 0x98, 0x3f, 0x6f, 0x5d, 0x19, 0x36, 0x67, 0x8d, 0x45, 0x47, 0x05, 0xbe, 0x46, 0xec,
	0x48, 0xff, 0x6a, 0x24, 0xd7, 0x39, 0xf8, 0xfb, 0x77, 0xb6, 0x55, 0xed, 0xca, 0x2b, 0x9e, 0x7c,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xb4, 0x0b, 0xad, 0xd3, 0x01, 0x00, 0x00,
}
